jedi: &jedi
  name: "jedi"
  level: 8
  offensive_objects:
    - lightsaber
    - force
  defense_objects:
    - force


droid: &droid
  name: "droid"
  level: 5
  offensive_objects:
    - trap
  defense_objects:
    - armor


pilot: &pilot
  name: "pilot"
  level: 7
  offensive_objects:
    - laser_gun
  defense_objects:
    - spaceship


card_types: &card_types
  jedi:
    <<: *jedi
  droid:
    <<: *droid
  pilot:
    <<: *pilot

development:
  <<: *card_types

test:
  <<: *card_types

production:
  <<: *card_types
