jedi: &jedi
  name: "jedi"
  offensive_objects:
    lightsaber: 7
    force: 8
  defense_objects:
    force: 6
  level: 8

droid: &droid
  name: "droid"
  offensive_objects:
    trap: 5
  defense_objects:
    armor: 8
  level: 5

pilot: &pilot
  name: "pilot"
  offensive_objects:
    laser_gun: 6
  defense_objects:
    spaceship: 9
  level: 7

card_types: &card_types
  jedi:
    <<: *jedi
  droid:
    <<: *droid
  pilot:
    <<: *pilot

development:
  <<: *card_types

test:
  <<: *card_types

production:
  <<: *card_types
