jedi: &jedi
  name: "jedi"
  offensive_objects:
    - lightsaber
    - force
  defense_objects:
    - force
  level: 8

droid: &droid
  name: "droid"
  offensive_objects:
    - trap
  defense_objects:
    - armor
  level: 5

pilot: &pilot
  name: "pilot"
  offensive_objects:
    - laser_gun
  defense_objects:
    - spaceship
  level: 7

card_types: &card_types
  jedi:
    <<: *jedi
  droid:
    <<: *droid
  pilot:
    <<: *pilot

development:
  <<: *card_types

test:
  <<: *card_types

production:
  <<: *card_types
