# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 877bc478ac10ccf1c04541fe0627a73f67aca1e5df40f305747073db9d3f0bc9222b6782e585f2c2641db4a6ecadf3fc8024c22a8ddb9f02b4d507e26729a601

test:
  secret_key_base: 8f4e215c917a7e6b60c3467f48efd5464cf79a3654fe4963e8b2dc5f7da0b5d286469387622b4948d36c3364fbec1ee142f6786e086f616d408e0cf523ed04f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
